feat: support multiple audiences
kinde-oss/kinde-typescript-sdk pull request #44
Opened 2024-01-17 22:25 UTC by peterphanouvong

# Explain your changes
- allow passing in audiences as string of audiences separated by whitespace
- set the url params in a way to allow for more than 1 audience

_Suppose there is a related issue with enough detail for a reviewer to understand your changes fully. In that case, you can omit an explanation and instead include either “Fixes #XX” or “Updates #XX” where “XX” is the issue number._

# Checklist

- [x] I have read the [“Pull requests” section](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md#pull-requests) in the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md).

🛟 _If you need help, consider asking for advice over in the [Kinde community](https://thekindecommunity.slack.com)._

2024-01-17 23:35 UTC, DaveOrDead requested changes

2024-01-17 23:35 UTC, DaveOrDead commented on lib/sdk/oauth2-flows/AuthCodeAbstract.ts
> +        urlSearchParams.append('audience', aud);
@peterphanouvong I think you want `searchParams`

2024-01-17 23:35 UTC, DaveOrDead commented on lib/sdk/oauth2-flows/ClientCredentials.ts
> +        urlSearchParams.append('audience', aud);
@peterphanouvong I think you want `searchParams`

2024-01-18 00:06 UTC, coel commented
@peterphanouvong, I'd suggest instead of doing a string split convert the property `config.audience` to be an array.  It could be `string` or `string[]` to maintain backwards compatibility.

So for `OAuth2FlowOptions`, the property becomes:

```  audience?: string | string[];```

Then check later if it is an array or not.  Could be a condition or do something to make an array if not like:

```      const audienceArray = Array.isArray(this.config.audience) ? this.config.audience : [this.config.audience];```

2024-01-18 00:10 UTC, DaveOrDead commented
@coel I guess a lot of the time the audience is being passed in via a `.env` file which would mean declaring

```
AUDIENCE=['a','b']
```
and then having to do some nastiness to convert that environment variable string into an array?

2024-01-18 22:14 UTC, coel commented
@DaveOrDead , I think if it is nasty we shouldn't force it onto users in the base SDK.  It seems like whitespace is valid in an audience, though we don't seem to handle it.  We might need to patch that up.

If we have helpers to deal with .env I think it should happen in the layer .env is introduced.

2024-01-18 22:54 UTC, DaveOrDead commented
@coel I'm ok with that @peterphanouvong are you ok to update?

2024-01-23 01:06 UTC, coel approved these changes

2024-01-23 21:56 UTC, DaveOrDead approved these changes

2024-01-23 21:56 UTC, merged